services:
  datalinq.code:
    image: ${DOCKER_REGISTRY-}datalinqcode
    build:
      context: .
      dockerfile: web/DataLinq.Code/Dockerfile
    ports:
    - "5001:5001" 
    volumes:
    - ./https.pfx:/https/https.pfx
    environment:
    - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/https.pfx
    - ASPNETCORE_Kestrel__Certificates__Default__Password=p455w0rd

  datalinq.api:
    image: ${DOCKER_REGISTRY-}datalinqapi
    build:
      context: .
      dockerfile: web/DataLinq.Api/Dockerfile
    ports:
    - "6000:6000"
    - "6001:6001" 
    volumes:
    - C:\DataLinq\Data\datalinq-storage:/app/DataLinq/storage
    - ./https.pfx:/https/https.pfx
    environment:
    - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/https.pfx
    - ASPNETCORE_Kestrel__Certificates__Default__Password=p455w0rd
