services:
  datalinq.code:
    image: datalinq.code:latest
    ports:
      - "5001:5001"
    volumes:
      - ./https.pfx:/https/https.pfx
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/https.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=p455w0rd
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTPS_PORTS=5001
      - DataLinq.Code__Instances__0__Name=DataLinq.CodeApi
      - DataLinq.Code__Instances__0__Description=DataLinq.CodeApi instance for testing and development
      - DataLinq.Code__Instances__0__LoginUrl=https://localhost:6001
      - DataLinq.Code__Instances__0__LogoutUrl=https://localhost:6001
      - DataLinq.Code__Instances__0__CodeApiClientUrl=https://datalinq.api:6001

  datalinq.api:
    image: datalinq.api:latest
    ports:
      - "6000:6000"
      - "6001:6001"
    volumes:
      - ./https.pfx:/https/https.pfx
      - ./DataLinqStorage:/app/DataLinq/storage
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/https.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=p455w0rd
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=6000
      - ASPNETCORE_HTTPS_PORTS=6001
      - DataLinq.Api__StoragePath=/app/DataLinq/storage
      - DataLinq.CodeApi__AccessTokenIssuer=https://localhost:6001
      - DataLinq.CodeApi__ClientEndpoints__0=https://localhost
